development:
  adapter: postgresql
  encoding: unicode
  database: testtest_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: testtest_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: testtest_production
  pool: 5

